!======================================================================+
!   READ_netCDF
!   Module to read from netCDF files
!======================================================================+
!
!   Contact information:
!   Garry Hayman
!   Centre for Ecology and Hydrology
!   Wallingford
!   Oxfordshire, OX10 8BB
!   United Kingdom
!   
!   email: garr@ceh.ac.uk
!   http://www.ceh.ac.uk
!
!   Development history
!
!   Date      Version     Author      Description
!   01/14      1.0        GDH         Initial version developed from
!                                     cdf2fortran.f
!
!   11/19      1.1        GDH         Release version
!
!======================================================================+

!   This contains subroutines and functions

!   READ_netCDF
!   READ_netCDF_info
!   READ_netCDF_varinfo
!   READ_netCDF_get_vardata_1D_int
!   READ_netCDF_get_vardata_2D_int
!   READ_netCDF_get_vardata_3D_int
!   READ_netCDF_get_vardata_1D_real
!   READ_netCDF_get_vardata_2D_real
!   READ_netCDF_get_vardata_3D_real
!   handle_err

!   Uses: netCDF calls

!   Do not forget to include the -I path_to_netcdf_includes in your
!   compile statement

!======================================================================+
MODULE MODULE_READ_netCDF
!======================================================================+

      USE                                       netCDF

!   Declaration of Parameters/Variables common to
!   all routines and modules

      IMPLICIT                                  NONE

!   Define limits for arrays:

      INTEGER,PARAMETER                         :: &
            max_vars   = 10, &
            max_dims   = 10

!   netCDF Parameters

      INTEGER                                   :: &
            ngatts,status

      CHARACTER (len=50)                        :: &
            netcdf_routine

      SAVE


CONTAINS

!======================================================================+
    SUBROUTINE READ_netCDF_open(cdfinput,ncid)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(OUT)                       :: &
            ncid

      CHARACTER (len=100),INTENT(IN)            :: &
            cdfinput                            ! netCDF filename

!-----------------------------------------------------------------------
!   Open netCDF file 
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_open'

!   netCDF call to open netCDF file using netCDF FORTRAN interface

      status = NF90_OPEN(cdfinput,0,ncid)
      IF (status .ne. NF90_NOERR) &
          CALL handle_err(netcdf_routine,status)

      WRITE(6,*) 'netCDF file opened ...'

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_open
!======================================================================+
    SUBROUTINE READ_netCDF_close(ncid)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(IN)                        :: &
            ncid

!-----------------------------------------------------------------------
!   Open netCDF file 
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_close'

!   netCDF call to open netCDF file using netCDF FORTRAN interface

      status = NF90_CLOSE(ncid)
      IF (status .ne. NF90_NOERR) &
          CALL handle_err(netcdf_routine,status)

      WRITE(6,*) 'netCDF file closed ...'

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_close
!======================================================================+
    SUBROUTINE READ_netCDF_info(ncid,ndims,nvars,indvname,indvdim,     &
               debug)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(IN)                        :: &
            ncid

      INTEGER,INTENT(OUT)                       :: &
            ndims,nvars,indvdim(max_dims)

      INTEGER                                   :: &
            unlimid,idim

      CHARACTER (len= 1),INTENT(IN)             :: &
            debug

      CHARACTER (len= 30),INTENT(OUT)           :: &
            indvname(max_dims)

!-----------------------------------------------------------------------
!   Retrieve key parameters from netCDF file
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_info'

!   netCDF call to inquire about structure of netCDF datafile:
!     ncid      - netCDF file identifier
!     ndims     - maximum number of dimensions 
!     nvars     - number of variables held in the netCDF file 
!     ngatts    - number of global attributes
!     ncid      - netCDF file identifier
!     unlimid   - identifier for unlimited dimension 

      status = NF90_INQUIRE(ncid,ndims,nvars,ngatts,unlimid)
      IF (status .ne. NF90_NOERR) &
          CALL handle_err(netcdf_routine,status)

      IF (debug == 'Y') THEN
         WRITE(6,*) 
         WRITE(6,'(1x,A30,I6)')    &
                  'status: NF90_INQUIRE_DIMENSION',status
         WRITE(6,'(1x,A30,I6)')    &
                  'ncid                          ',ncid
         WRITE(6,'(1x,A30,I6)')    &
                  'ndims                         ',ndims
         WRITE(6,'(1x,A30,I6)')    &
                  'nvars                         ',nvars
         WRITE(6,'(1x,A30,I6)')    &
                  'ngatts                        ',ngatts
         WRITE(6,'(1x,A30,I6)')    &
                  'unlimid                       ',unlimid
      END IF

      DO idim = 1,ndims

!   Loop over each independent variable

!   netCDF call to inquire about dimensions of independent variables:
!      ncid      - netCDF file identifier
!      idim      - dimension index
!      indvname  - array with names of independent variables
!      indvdim   - number of elements for the independent variables

         status = NF90_INQUIRE_DIMENSION(ncid, idim, indvname(idim), indvdim(idim))
         IF (status .ne. NF90_NOERR) &
             CALL handle_err(netcdf_routine,status)

         IF (debug == 'Y') THEN
            WRITE(6,*) 
            WRITE(6,'(1x,A30,I6)') &
                  'status: NF90_INQUIRE_DIMENSION',status
            WRITE(6,'(1x,A30,I6)') &
                  'ncid                          ',ncid
            WRITE(6,'(1x,A30,I6)') &
                  'dimension number              ',idim
            WRITE(6,'(1x,A30,1x,A40)') &
                  'independent variable name     ',indvname(idim)
            WRITE(6,'(1x,A30,I6)') &
                  'dimension                     ',indvdim(idim)
         END IF

      ENDDO

      WRITE(6,*)

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_info

!======================================================================+
    SUBROUTINE READ_netCDF_varinfo(ncid,nvars,var_names,var_ids, &
               nvar_dims,var_dimids,debug)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(IN)                        :: &
            ncid

      INTEGER,INTENT(INOUT)                     :: &
            nvars

      INTEGER,INTENT(OUT)                       :: &
            var_ids(max_vars), &
            nvar_dims(max_vars), &
            var_dimids(max_vars,max_dims)

      INTEGER                                   :: &
            idim,ndims,ivar,var_type,var_id, &
            nvar_att(max_vars),dimids(max_dims)

      CHARACTER (len=  1),INTENT(IN)            :: &
            debug

      CHARACTER (len= 30),INTENT(OUT)           :: &
            var_names(max_vars)

!-----------------------------------------------------------------------
!   Retrieve key parameters from netCDF file
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_varinfo'

!   netCDF call to inquire about dependent variable properties:
!     ncid      - netCDF file identifier
!     idvar     - array with position order of required variable
!     varnames  - name of dependent variable
!     vartype   - integer code for type of array INTEGER, REAL, etc 
!     vardims   - number of dimensions to dependent variable
!     varids    - array with dimension identifiers
!     varatt    - dependent variable attributes

      status = NF90_INQ_VARIDS(ncid,nvars,var_ids)
      IF (status .ne. NF90_NOERR) &
          CALL HANDLE_ERR(netcdf_routine,status)

      DO ivar=1,nvars

         var_id                   = var_ids(ivar)

         status = NF90_INQUIRE_VARIABLE(ncid,var_id,var_names(ivar), &
                var_type,ndims,dimids,nvar_att(ivar))
         IF (status .ne. NF90_NOERR) &
             CALL HANDLE_ERR(netcdf_routine,status)

         nvar_dims(ivar)          = ndims 
         var_dimids(ivar,1:ndims) = dimids(1:ndims)

         IF (debug == 'Y') THEN
            WRITE(6,'(1X,A30,4I6)') var_names(ivar),ivar,var_type, &
                  var_ids(ivar),nvar_dims(ivar)
            WRITE(6,'(31X,10I6)')   (var_dimids(ivar,idim),idim=1,ndims)
         END IF

      END DO              ! Loop over number of variables

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_varinfo

!======================================================================+
    SUBROUTINE READ_netCDF_get_vardata_1D_int(ncid,var_id,ndim1, &
               var_data,debug)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(IN)                        :: &
            ncid,var_id,ndim1

      INTEGER,DIMENSION(ndim1),INTENT(OUT)      :: &
            var_data

      CHARACTER (len= 1),INTENT(IN)             :: &
            debug

!-----------------------------------------------------------------------
!   Open netCDF file and retrieve variable data 
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_get_vardata_1D_int'

!   netCDF call to open netCDF file using netCDF FORTRAN interface

      status = NF90_GET_VAR(ncid,var_id,var_data)
      IF (status .ne. NF90_NOERR) &
          CALL handle_err(netcdf_routine,status)

      WRITE(6,*) 'Data successfully read from netCDF file ...'

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_get_vardata_1D_int

!======================================================================+
    SUBROUTINE READ_netCDF_get_vardata_2D_int(ncid,var_id, &
               ndim1,ndim2,var_data,debug)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(IN)                        :: &
            ncid,var_id,ndim1,ndim2

      INTEGER,DIMENSION(ndim1,ndim2),INTENT(OUT):: &
            var_data

      CHARACTER (len= 1),INTENT(IN)             :: &
            debug

!-----------------------------------------------------------------------
!   Open netCDF file and retrieve variable data 
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_get_vardata_2D_int'

!   netCDF call to open netCDF file using netCDF FORTRAN interface

      status = NF90_GET_VAR(ncid,var_id,var_data)
      IF (status .ne. NF90_NOERR) &
          CALL handle_err(netcdf_routine,status)

      WRITE(6,*) 'Data successfully read from netCDF file ...'

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_get_vardata_2D_int

!======================================================================+
    SUBROUTINE READ_netCDF_get_vardata_3D_int(ncid,var_id, &
               ndim1,ndim2,ndim3,var_data,debug)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(IN)                        :: &
            ncid,var_id,ndim1,ndim2,ndim3

      INTEGER,DIMENSION(ndim1,ndim2,ndim3),INTENT(OUT):: &
            var_data

      CHARACTER (len= 1),INTENT(IN)             :: &
            debug

!-----------------------------------------------------------------------
!   Open netCDF file and retrieve variable data 
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_get_vardata_3D_int'

!   netCDF call to open netCDF file using netCDF FORTRAN interface

      status = NF90_GET_VAR(ncid,var_id,var_data)
      IF (status .ne. NF90_NOERR) &
          CALL handle_err(netcdf_routine,status)

      WRITE(6,*) 'Data successfully read from netCDF file ...'

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_get_vardata_3D_int

!======================================================================+
    SUBROUTINE READ_netCDF_get_vardata_1D_real(ncid,var_id,ndim1, &
               var_data,debug)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(IN)                        :: &
            ncid,var_id,ndim1

      REAL,DIMENSION(ndim1),INTENT(OUT)         :: &
            var_data

      CHARACTER (len= 1),INTENT(IN)             :: &
            debug

!-----------------------------------------------------------------------
!   Open netCDF file and retrieve variable data 
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_get_vardata_1D_real'

!   netCDF call to open netCDF file using netCDF FORTRAN interface

      status = NF90_GET_VAR(ncid,var_id,var_data)
      IF (status .ne. NF90_NOERR) &
          CALL handle_err(netcdf_routine,status)

      WRITE(6,*) 'Data successfully read from netCDF file ...'

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_get_vardata_1D_real

!======================================================================+
    SUBROUTINE READ_netCDF_get_vardata_2D_real(ncid,var_id, &
               ndim1,ndim2,var_data,debug)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(IN)                        :: &
            ncid,var_id,ndim1,ndim2

      REAL,DIMENSION(ndim1,ndim2),INTENT(OUT)   :: &
            var_data

      CHARACTER (len= 1),INTENT(IN)             :: &
            debug

!-----------------------------------------------------------------------
!   Open netCDF file and retrieve variable data 
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_get_vardata_2D_real'

!   netCDF call to open netCDF file using netCDF FORTRAN interface

      status = NF90_GET_VAR(ncid,var_id,var_data)
      IF (status .ne. NF90_NOERR) &
          CALL handle_err(netcdf_routine,status)

      WRITE(6,*) 'Data successfully read from netCDF file ...'

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_get_vardata_2D_real

!======================================================================+
    SUBROUTINE READ_netCDF_get_vardata_3D_real(ncid,var_id, &
               ndim1,ndim2,ndim3,var_data,debug)
!======================================================================+

!   This file is a fortran template file designed to read the given
!   netCDF file into memory.  Adapted from code generated by
!   cdf2fortran.f

!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

!   Definition of netCDF parameters and variables

      INTEGER,INTENT(IN)                        :: &
            ncid,var_id,ndim1,ndim2,ndim3

      REAL,DIMENSION(ndim1,ndim2,ndim3),INTENT(OUT) :: &
            var_data

      CHARACTER (len= 1),INTENT(IN)             :: &
            debug

!-----------------------------------------------------------------------
!   Open netCDF file and retrieve variable data 
!-----------------------------------------------------------------------

      netcdf_routine = 'READ_netCDF_get_vardata_3D_real'

!   netCDF call to open netCDF file using netCDF FORTRAN interface

      status = NF90_GET_VAR(ncid,var_id,var_data)
      IF (status .ne. NF90_NOERR) &
          CALL handle_err(netcdf_routine,status)

      WRITE(6,*) 'Data successfully read from netCDF file ...'

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE READ_netCDF_get_vardata_3D_real

!======================================================================+
    SUBROUTINE handle_err(routine,status)
!======================================================================+
!   Code taken from page 8 of NetCDF Fortran 77 Interface Guide
!   Updated to FORTRAN 90
!-----------------------------------------------------------------------

      IMPLICIT                                  NONE

      INTEGER,INTENT(IN)                        :: &
            status

      CHARACTER (len=50)                        :: &
            routine
!-----------------------------------------------------------------------

      IF (status .NE. NF90_NOERR) THEN
         PRINT *
         PRINT *, 'In routine: ',routine
         PRINT *, NF90_STRERROR(status)
         STOP 'Stopped'
      ENDIF

!-----------------------------------------------------------------------
!   Return to calling routine
!-----------------------------------------------------------------------
      RETURN

    END SUBROUTINE handle_err

!======================================================================+
END MODULE MODULE_READ_netCDF
!======================================================================+
